SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS the_Wall_DB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE the_Wall_DB;


CREATE TABLE IF NOT EXISTS users (
    user_id		INT						NOT NULL		AUTO_INCREMENT	PRIMARY KEY,
    user_uniq	VARCHAR(255)	NULL,
    first_name	VARCHAR(100)	NOT NULL,
    last_name	VARCHAR(100)	NOT NULL,
    email			VARCHAR(255)	NOT NULL,
    passcode		VARCHAR(255)	NOT NULL,
    birth_date	VARCHAR(10)	NULL,
    created_at	DATETIME			NULL,
    updated_at	DATETIME			NULL
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS messages (
	message_id		INT						NOT NULL		AUTO_INCREMENT	PRIMARY KEY,
    user_id			INT						NOT NULL,
    user_msg		TEXT					NOT NULL,
    created_at		DATETIME			NULL,
    updated_at		DATETIME			NULL,
    FOREIGN KEY (user_id)	REFERENCES users(user_id)	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS comments (
	comment_id	INT						NOT NULL		AUTO_INCREMENT	PRIMARY KEY,
	message_id		INT						NOT NULL,
    user_id			INT						NOT NULL,
    user_cmnt		TEXT					NOT NULL,
    created_at		DATETIME			NULL,
    updated_at		DATETIME			NULL,
    FOREIGN KEY (message_id)		REFERENCES messages(message_id)	ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (user_id)	REFERENCES users(user_id)	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
